FROM tinygo/tinygo:0.19.0 AS builder

RUN apt-get update && apt-get install -y git

ENV GOPATH=/go

COPY main.go .
COPY envoy.yaml .

# generate a go.mod for getting proxy-wasm sdk dependency
RUN go mod init test && go mod tidy

RUN tinygo build -o ./http-headers-logs.wasm -scheduler=none -target=wasi ./main.go

FROM envoyproxy/envoy-dev:eb99bfc13150fe57405138af3a6f1751fad7d8e2

COPY --from=builder envoy.yaml /envoy.yaml
COPY --from=builder http-headers-logs.wasm /http-headers-logs.wasm

RUN chmod go+r /envoy.yaml && \
    chmod go+r /http-headers-logs.wasm && \
    mkdir logs && chmod ugo+rw logs